# Generated by Django 3.2.4 on 2021-06-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=60, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('Nombre', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Nombre del manga ')),
                ('idioma', models.CharField(max_length=20, verbose_name='Idioma del Manga')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
