# Generated by Django 3.2.4 on 2021-06-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manga_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen del Manga'),
        ),
    ]
