# Generated by Django 3.2.4 on 2021-06-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_manga_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
